zooniverse/education-api

- app/controllers/teacher_area_controller.rb
- app/models/classroom.rb
- app/models/student_user.rb
- app/operations/classrooms/join.rb
- app/operations/classrooms/teacher_create.rb
- app/serializers/classroom_serializer.rb
- app/serializers/user_serializer.rb
- db/migrate/20160303163147_add_student_users.rb
- db/migrate/20160303164604_add_classroom_metadata.rb
- db/migrate/20160304113431_add_zoo_login_display_name_to_users.rb
- db/schema.rb
- spec/controllers/teachers/classrooms_controller_spec.rb
- spec/operations/classrooms/join_spec.rb
- spec/spec_helper.rb
> [WIP] Students

- app/models/user.rb
- spec/controllers/teachers/classrooms_controller_spec.rb
Towards zooniverse/wildcam-gorongosa-education#6
> Set login/display_name

- .ruby-style.yml
- app/models/carto_transformer.rb
- app/models/carto_uploader.rb
- app/models/cartodb.rb
- app/operations/classifications/process_export.rb
- spec/models/carto_transformer_spec.rb
- spec/models/carto_uploader_spec.rb
Closes #9 
* This PR is intended to improve the data sync between new Classifications data from Panoptes to CartoDB.
* NOT addressed: anything to do with Aggregations or Subjects data.
> Improve CartoDB Transformer & Uploader (Classifications) [Ready for review, needs 'live' testing]

- .hound.yml
- app/models/carto_transformer.rb
- app/models/carto_uploader.rb
This prepares for the fixed annotation format
> Make sure we can handle the new annotation format too

- app/controllers/downloads_controller.rb
- config/routes.rb
To use this, do a POST request to `/downloads`:
```html
<form method="post" action="https://education-api.zooniverse.org/downloads">
<input type="hidden" name="filename" value="foobar.csv">
<input type="hidden" name="content_type" value="text/csv">
<input type="hidden" name="data" value="1,2,3,4">
</form>
```
> Add downloads echo service

- app/controllers/application_controller.rb
Kept the wrong line when resolving a merge.
> Fix mismerged line in app controller

- app/controllers/projects_controller.rb
- spec/controllers/projects_controller_spec.rb
> Fixes panoptes client project search syntax

- db/migrate/20170901174114_refactor_projects_to_programs.rb
Fixes a migration (that hasn't run on production yet) that will cause PG to complain about existing projects.
> Remove null false on field without default

- config/initializers/revision.rb
- spec/controllers/students/classrooms_controller_spec.rb
> Fixes incorrect filename

- app/controllers/application_controller.rb
- app/controllers/teachers/classrooms_controller.rb
- app/operations/classrooms/teacher_create.rb
- spec/controllers/teachers/classrooms_controller_spec.rb
- spec/operations/classrooms/student_index_spec.rb
- spec/operations/classrooms/teacher_create_spec.rb
Classrooms weren't being created with valid programs. The program relationship is mandatory in the classroom create payload and they're now created directly on the given program.
> Create classroom on program to associate on create

- Dockerfile
- config/puma.rb
To make things simpler to set up in Swarm, I'm reconfiguring everything to listen on port 80.
> Listen on port 80

- app/controllers/application_controller.rb
Like Caesar, hopefully to allow the newer Ruby client to use the app credentials to create workflows properly.
> Adds admin param to app client request

- app/controllers/application_controller.rb
- app/workers/worker_helpers.rb
Add it to the worker helper, too.
> Add admin param

- Gemfile
- Gemfile.lock
- config/environments/production.rb
This should just replace the Rails logger entirely and shunt logs over UDP to Graylog.
> Adds Graylogging

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
Return to logstash and associated configs.
> Logstash wins

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
> Logstasher env config updates

- config/environments/production.rb
- config/environments/staging.rb
> Fix typo in config

- kinesis-to-http/function.py
Leaving the old GZ 101 project for now for the transition. I believe this is required to have the classification counters work.
> Add project 9908 to kinesis-to-http function

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
> Adds k8s resource limits

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
builds on #269 and adds a production sidekiq pod container
> Add Prod sidekiq k8s deployment

- kinesis-to-http/lambda.json
ensure we know what this lambda is for
> add the linked service to the desc

- .github/workflows/db_migration_staging.yml
- kubernetes/db-migration-staging.tmpl
Also include the commit SHA in the db migration job.
> Add staging db migration template

- .github/workflows/build_and_push_image.yml
- kubernetes/db-migrate-staging.tmpl
Volume mount required to mount secret file. Image build/push included so that the migration job has something new to pull.
> Add volume mount & image builds on PR updates
