app/models/carto_transformer.rb
* I forgot to add `workflow_id` to the Classifications that we send to CartoDB. Oops! Fixed now.
* Note that the `wildcam_classifications` [DB table](https://shaunanoordin-zooniverse.carto.com/tables/wildcam_classifications) had to be modified for this purpose.
For future use, use this CSV as a 'starter seed' to create a fresh `wildcam_classifications` table, modifying `classification_id` to a large enough value so we'll only export recent (students-only) classifications.
```
species_horns,species_interacting,species_eating,species_standing,species_resting,species_moving,species_young,species_count,subject_id,classification_id,species,gorongosa_id,user_group_ids,user_name,workflow_id,classified_at
false,false,true,true,true,true,false,50+,894374,13374904,Baboon,21484_1000_D23_Season 3_Set …
```
=> Added 'workflow_id' to CartoDB Export

app/operations/assignments/create.rb
Fixes a 500 server error that prevents Teachers on WGL from creating new Assignments.
TL;DR: **We cannot create a new Subject Set with `subjects` set to an empty array `[]`. Either set some valid subject IDs, or don't put anything at all.**
When attempting to Create new Assignments on lab.wildcamgorongosa.org/teachers/classrooms, clicking on the "Submit" button will cause the application to break.
Looking into the browser console, we see that the call to /assignments in the Education API returns a 500 Internal Server error.
Looking into the logs of the Education API, we see this error:
```
I, [2016-10-12T15:02:40.131201 #51]  INFO -- : Started POST "/assignments/" for 163.1.246.64 at 2016-10-12 15:02:40 +0000
I, [2016-10-12T15:02:40.133719 #51]  INFO -- : Processing by …
```
=> Fix Create New Assignment's 500 error

config/initializers/active_model_serializers.rb
Upgrading AMS from 0.10.rc4 to 0.10.6 added a new default to dasherize JSON keys, which apparently is in the JSON API spec, but our frontend can't handle that.
=> Configure AMS to keep underscores

app/controllers/application_controller.rb, app/controllers/assignments_controller.rb, app/workers/worker_helpers.rb
The different platform clients got consolidated which removed the URL keyword. It's now determined by the env automatically.
=> Remove URL arg from Panoptes::Client.new

app/operations/projects/create.rb
forgot to update the Project create op when I made this change originally.
=> Base workflow id is an int, not a bool

app/controllers/teachers/classrooms_controller.rb, app/operations/classrooms/teacher_show.rb
Wildcam just grabs all a teacher's classrooms and filters them by id on the front end. For other projects, teachers will likely create many more classrooms, making this method not only unwieldy but problematic due to paging. Just grab the one you need.
=> Adds show route for /teachers/classrooms/:id

app/operations/classrooms/teacher_show.rb
...rather than show the query in the error response.
=> Raise an exception if the record is not found

app/operations/classrooms/teacher_show.rb
Reverts zooniverse/education-api#60
#find already raises an exception, gross sql is just in the AR::RecordNotFound message. Sure.
=> Revert "Raise an exception if the record is not found"

app/controllers/programs_controller.rb, app/controllers/student_area_controller.rb, app/operations/classrooms/teacher_create.rb, app/operations/classrooms/teacher_update.rb, app/operations/programs/index.rb, app/operations/programs/show.rb
* `GET /programs` and `GET /program/:id` are now public.
* Classroom create and update ops now list program as a relationship so they'll be properly associated.
Fixes #69
=> Publicize GET programs routes

app/operations/classrooms/student_index.rb, app/operations/classrooms/teacher_index.rb, spec/controllers/teachers/classrooms_controller_spec.rb, spec/factories/classroom_factories.rb, spec/operations/assignments/create_spec.rb, spec/operations/classrooms/student_index_spec.rb, spec/operations/classrooms/teacher_index_spec.rb
All valid classrooms should have one (despite existing data that needs updating) and this will prevent confusion when nothing (or invalid classrooms) is returned when the param is left out.
Also added the association to the classroom factory to represent this requirement.
=> Require program_id param on classroom index routes

app/operations/classrooms/join.rb, app/operations/classrooms/teacher_index.rb, spec/controllers/students/classrooms_controller_spec.rb, spec/controllers/teachers/classrooms_controller_spec.rb, spec/factories/classroom_factories.rb, spec/operations/assignments/create_spec.rb, spec/operations/classrooms/join_spec.rb, spec/operations/classrooms/student_index_spec.rb, spec/operations/classrooms/teacher_index_spec.rb
For "custom" (Wildcam-style, custom assignment) programs, teachers create assignments before or after a classroom is joined and then assign them to students. However, for non-custom (i2a) programs, the order of operations will look more like this:
1) Teacher creates classroom
2) Default assignments are automatically generated by the i2a frontend.
3) Stutent attempts to join classroom and is automatically assigned each of the classroom's assignments.
This PR adds that check, based on the program's `custom` attribute, and assigns them if it is false. Programs are now required by all classroom requests and are an included association in the classroom factory.
=> Default assignments on classroom join

Gemfile.lock, app/operations/assignments/create.rb, spec/controllers/assignments_controller_spec.rb, spec/operations/assignments/create_spec.rb
Assignments weren't being created correctly on custom programs. This was because programs != programs and subject sets need a project. Now, the assignment creation order of operations looks like this:
is the program custom (wildcam-style)?
* clone the workflow indicated in request
* create and fill subject set using project id from response from above
* link that subject set to the cloned workflow
* create assignment (incl. workflow_id = cloned workflow id and subject_set_id)
not custom? (i2a-alike)
* get workflow data from panoptes using id in request
* create assignment (incl. assignment.workflow_id = workflow id )
Required an additional call to panoptes because the project id is needed before the workflow is cloned, but not really an issue. Also required addition of a client method on …
=> Refactor of assignment creation

app/operations/assignments/update.rb, app/operations/classrooms/teacher_create.rb, app/operations/classrooms/teacher_update.rb, spec/operations/classrooms/teacher_create_spec.rb, spec/operations/classrooms/teacher_update_spec.rb
Attributes were being ignored because the classroom wasn't being saved after updating the object in the operation. This wasn't being caught by the spec because the test object wasn't being reloaded from the db before testing it. Also fixed the update op so that it won't update non-included attributes to nil.
Fixes https://github.com/zooniverse/education-api/issues/83
=> Fix classroom creation

app/operations/kinesis/count_classification.rb, spec/fixtures/example_kinesis_payload.json, spec/operations/kinesis/count_classification_spec.rb
Non-custom (i2a-style) projects include a "user group" key in the classification metadata that indicates the specific UG/classroom that should be incremented. 
This PR ensures that in these cases, only the single classroom's counter is incremented rather than the corresponding classroom for every non-ID user group the user is in. 
This latter case seems to be the desired behavior for Wildcam-style projects, so if there is no user group included in the classfication metadata (i.e. there was no query param on the URL during classification) then they'll all be ticked as before.
Sorry that the spec diff is a little gross, it's just doubling them into two separate contexts (with UG and w/o).
=> Count classifications by single user group

app/operations/kinesis/count_classification.rb, spec/operations/kinesis/count_classification_spec.rb
A classification comes in over the kinesis stream. If the `selected_user_group_id` param is blank, increment all the assignment counters as expected (Wildcam). However, if that param exists, only update the StudentAssignment counter if that assignment's classroom's zooniverse group ID matches. This was already fixed for classrooms.
=> Non-UG assignment counters shouldn't increment

config/routes.rb, docker-compose.yml
and Protect against timing attacks:
See https://codahale.com/a-lesson-in-timing-attacks/
See https://thisdata.com/blog/timing-attacks-against-string-comparison/
Use & (do not use &&) so that it doesn't short circuit.
Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
=> restrict access to sidekiq using basic authentication

app/controllers/application_controller.rb, spec/controllers/assignments_controller_spec.rb
Don't let `Panoptes::Client::ResourceNotFound` exceptions turn into 500s. This will catch them like ActiveRecord not-founds and return a more sensible 404.
=> Catches Panoptes API not-founds and treat them like ARs.

app/operations/assignments/create.rb, spec/operations/assignments/create_spec.rb
ensure education API cloned workflows do not pollute the linked project serialized responses, these are special workflows that are only accessed directly by ID
=> set the serialize_with_project attribute to false

Gemfile, Gemfile.lock, config/puma.rb
Update the gem. Remove Puma workaround from 2013.
Also, stop explicitly sending logs to files and let stdout get read by kubernetes.
=> Get New Relic working again

Dockerfile, Gemfile, Gemfile.lock
ruby 2.6 is EOL so we can safely bump to 2.7 https://www.ruby-lang.org/en/downloads/branches/
also we don't need sinatra to mount the sidekiq UI as we have rails...i'm not sure why it was added in https://github.com/zooniverse/education-api/commit/fd7447fc7ceb2881291886418d1e54b34e442271 so we can safely remove it from use in this repo
=> Remove sinatra gem and upgrade ruby to 2.7

kinesis-to-http/function.py, kinesis-to-http/lambda.json, kinesis-to-http/requirements.txt
Adds the project id of the new cloned Galaxy Zoo classrooms project to the list that the lambda will forward to EduAPI. 
Needs to be uploaded via `lambda-uploader`, deploying this PR will not do it.
=> Add new Galaxy Zoo project to lambda forwarder

app/operations/classrooms/teacher_create.rb, spec/controllers/teachers/classrooms_controller_spec.rb, spec/operations/classrooms/teacher_create_spec.rb
Update classroom creation so that associated panoptes user_group's display_name matches classroom.name
Part of https://www.figma.com/file/qbqbmR3t5XV6eKcpuRj7mG/Group-Stats?type=design&node-id=0-1&mode=design design efforts:
Want: Classroom name to be the associated Panoptes `User_group`'s `display_name`. 
Reason why this was not a want before: 
-  `user_group`s were almost treated like "second-class citizen tables" and with new stats features coming up we are treating them like "first-class"
=> Update classroom creation so that associated panoptes user_group's display_name matches classroom.name
